"use client"
import {useEffect,useState} from 'react'
import {useParams} from 'next/navigation'
import Link from 'next/link'
import {admissionSettingsApi,AdmissionFormConfig,AdmissionCustomField} from '@/lib/api'
import {emptyAdmissionBasicData} from '@/components/admission/AdmissionBasicFields'
import AdmissionFormView from '@/components/admission/AdmissionFormView'
import styles from '../page.module.css'
export default function AdmissionSettings(){
 const {id}=useParams();const [config,setConfig]=useState<AdmissionFormConfig|null>(null);const [version,setVersion]=useState<number|null>(null)
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [preview,setPreview]=useState(false)
 useEffect(()=>{let live=true;admissionSettingsApi.get(Number(id)).then(r=>{if(live){setConfig(r.configuration);setVersion(r.version)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[id])
 const changeField=(index:number,patch:Partial<AdmissionCustomField>)=>{if(config)setConfig({...config,fields:config.fields.map((f,i)=>i===index?{...f,...patch}:f)})}
 return <div className={styles.page}><Link href={`/dashboard/institution/${id}/settings`}>← Institution Settings</Link><h1 className={styles.title}>Admission Form</h1><p className={styles.sub}>Publish a new version for future applications. Existing applications keep their original fields and declaration. {version?`Current version: ${version}`:'Using the original institution form.'}</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}{config&&<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await admissionSettingsApi.publish(Number(id),{...config,common:{}});setVersion(r.version);setConfig(r.configuration);setMessage('New form version published.')}catch(e){setError(e instanceof Error?e.message:'Publishing failed')}finally{setBusy(false)}}}><fieldset disabled={busy} className={styles.fieldset}>
 <p>The standard admission form includes child, parent, address, guardian, sibling and identification details. Candidate email, phone and notes are not collected. Configure the parent declaration and any additional fields below.</p>
 <section className={styles.card}><h2 className={styles.heading}>Additional fields</h2>{config.fields.map((f,index)=><section key={f.id} style={{border:'1px solid #e2e8f0',padding:'1rem',marginBottom:'1rem',borderRadius:8}}><div className={styles.grid}><label className={styles.item}>Label<input required maxLength={150} value={f.label} onChange={e=>changeField(index,{label:e.target.value})}/></label><label className={styles.item}>Type<select value={f.type} onChange={e=>changeField(index,{type:e.target.value as AdmissionCustomField['type']})}>{['text','number','date','dropdown','boolean','long_text'].map(t=><option key={t}>{t}</option>)}</select></label><label className={styles.item}>Section<input required maxLength={100} value={f.section} onChange={e=>changeField(index,{section:e.target.value})}/></label>{f.type==='dropdown'&&<label className={styles.item}>Options (one per line)<textarea required value={f.options.join('\n')} onChange={e=>changeField(index,{options:e.target.value.split('\n')})}/></label>}</div><div className={styles.actions}>{(['required','show_in_print','save_to_profile'] as const).map(key=><label key={key}><input type="checkbox" checked={f[key]} onChange={e=>changeField(index,{[key]:e.target.checked})}/>{key.replaceAll('_',' ')}</label>)}<button type="button" className={styles.secondary} disabled={index===0} onClick={()=>{const fields=[...config.fields];[fields[index-1],fields[index]]=[fields[index],fields[index-1]];setConfig({...config,fields})}}>Move up</button><button className={styles.secondary} type="button" onClick={()=>setConfig({...config,fields:config.fields.filter((_,i)=>i!==index)})}>Remove</button></div></section>)}<button className={styles.secondary} type="button" disabled={config.fields.length>=60} onClick={()=>setConfig({...config,fields:[...config.fields,{id:'field_'+crypto.randomUUID().replaceAll('-',''),label:'',type:'text',section:'Additional details',options:[],required:false,show_in_print:true,save_to_profile:true}]})}>+ Add Field</button></section>
 <section className={styles.card}><h2 className={styles.heading}>Parent declaration</h2><label className={styles.item}>Declaration (one paragraph per line)<textarea rows={6} value={config.declaration.join('\n')} onChange={e=>setConfig({...config,declaration:e.target.value.split('\n')})}/></label></section>
 <section className={styles.card}><h2 className={styles.heading}>Print settings</h2><label className={styles.item}>Form theme colour<input type="color" value={config.theme_color||'#ed1722'} onChange={e=>setConfig({...config,theme_color:e.target.value})} style={{width:80,height:44,padding:4}}/></label><p>Uses the institution logo, name, address and contact details from Institution Settings, with a common A4 layout.</p><button type="button" className={styles.secondary} onClick={()=>setPreview(!preview)}>{preview?'Hide':'Show'} print preview</button>{preview&&<AdmissionFormView application={{id:0,institution_id:Number(id),reference:'PREVIEW',applicant_name:'Student name',email:null,template_version:'common_v1',extra_data:{...emptyAdmissionBasicData(),_form:config,_answers:{}},admitted_on:null,phone:'',date_of_birth:'',gender:'',address:'',guardian_name:'',guardian_phone:'',academic_year:'',grade:'',notes:'',status:'submitted',student_id:null}}/>}</section>
 <div className={`${styles.actions} ${styles.publishActions}`}><button type="submit" className={styles.publishButton}>{busy?'Publishing…':'Publish Form Version'}</button></div></fieldset></form>}</div>
}
