"use client"
import styles from '@/app/dashboard/institution/[id]/accounts/invoices/create/create.module.css'
import local from './AdmissionBasicFields.module.css'
export const emptyAdmissionBasicData = () => ({aadhaar:'',nationality:'',religion:'',caste:'',mother_tongue:'',blood_group:'',identification_mark_1:'',identification_mark_2:'',father:{name:'',occupation:'',qualification:'',phone:''},mother:{name:'',occupation:'',qualification:'',phone:''},parent_email:'',official_address:'',communication_address:'',stays_with_parents:true,local_guardian_name:'',local_guardian_address:'',local_guardian_mobile:'',local_guardian_landline:'',siblings:[] as {name:string;class_division:string}[],declaration_parent:'',declaration_date:'',declaration_place:'',signed_declaration_received:false})
export type AdmissionBasicData = ReturnType<typeof emptyAdmissionBasicData>
export default function AdmissionBasicFields({value,onChange,dob,year,declaration}:{value:AdmissionBasicData;onChange:(v:AdmissionBasicData)=>void;dob:string;year:string;declaration:string[]}){
 const field=(key:keyof AdmissionBasicData,label:string,max=100,type='text')=><label className={styles.field} key={key}>{label}<input className={styles.input} type={type} maxLength={max} pattern={key==='aadhaar'?'[0-9]{12}':undefined} value={String(value[key]||'')} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>
 const text=(key:keyof AdmissionBasicData,label:string)=><label className={styles.field} key={key}>{label}<textarea className={styles.input} rows={3} maxLength={2000} value={String(value[key]||'')} onChange={e=>onChange({...value,[key]:e.target.value})}/></label>
 let age='Enter date of birth and academic year to calculate age.'
 if(dob&&/^\d{4}-\d{2}(\d{2})?$/.test(year)){const born=new Date(dob+'T00:00:00');const cutoff=new Date(Number(year.slice(0,4)),5,1);const months=(cutoff.getFullYear()-born.getFullYear())*12+cutoff.getMonth()-born.getMonth()-(cutoff.getDate()<born.getDate()?1:0);age=months>=0?`Age on 1 June ${year.slice(0,4)}: ${Math.floor(months/12)} years, ${months%12} completed months`:'Date of birth is after the age calculation date.'}
 return <div className={local.sections}>
 <section><h2 className={styles.cardTitle}>Child’s additional details</h2><p className={styles.hint}>{age}. Date of birth in words is generated when saved.</p><div className={local.grid}>
 {field('aadhaar','Aadhaar number (optional)',12)}{field('nationality','Nationality')}{field('religion','Religion (optional)')}{field('caste','Caste (optional)')}{field('mother_tongue','Mother tongue')}
 <label className={styles.field}>Blood group<select className={styles.input} value={value.blood_group} onChange={e=>onChange({...value,blood_group:e.target.value})}><option value="">Unknown / not supplied</option>{['A+','A-','B+','B-','O+','O-','AB+','AB-'].map(g=><option key={g}>{g}</option>)}</select></label>
 {field('identification_mark_1','Identification mark 1',300)}{field('identification_mark_2','Identification mark 2',300)}</div></section>
 <section><h2 className={styles.cardTitle}>Details of parents</h2>{(['father','mother'] as const).map(parent=><div key={parent}><h3 className={local.subheading}>{parent==='father'?'Father':'Mother'}</h3><div className={local.grid}>{(['name','occupation','qualification','phone'] as const).map(key=><label className={styles.field} key={key}>{{name:'Name',occupation:'Occupation',qualification:'Educational qualification',phone:'Mobile / landline'}[key]}<input className={styles.input} maxLength={key==='phone'?50:key==='name'?200:150} value={value[parent][key]} onChange={e=>onChange({...value,[parent]:{...value[parent],[key]:e.target.value}})}/></label>)}</div></div>)}{field('parent_email','Parent contact email (optional)',255,'email')}</section>
 <section><h2 className={styles.cardTitle}>Addresses</h2><p className={styles.hint}>The address entered above is the permanent address.</p><div className={local.grid}>{text('official_address','Official address')}{text('communication_address','Address for communication')}</div></section>
 <section><h2 className={styles.cardTitle}>Local guardian</h2><label className={local.checkbox}><input type="checkbox" checked={value.stays_with_parents} onChange={e=>onChange({...value,stays_with_parents:e.target.checked})}/>Child stays with parents</label>{!value.stays_with_parents&&<><p className={styles.hint}>Guardian name, address and mobile are required.</p><div className={local.grid}>{field('local_guardian_name','Local guardian name',200)}{field('local_guardian_mobile','Mobile',20)}{field('local_guardian_landline','Landline',20)}{text('local_guardian_address','Local guardian address')}</div></>}</section>
 <section><h2 className={styles.cardTitle}>Brothers / sisters studying at this school</h2>{value.siblings.map((s,index)=><div className={local.sibling} key={index}><input className={styles.input} aria-label={`Sibling ${index+1} name`} placeholder="Name" required maxLength={200} value={s.name} onChange={e=>onChange({...value,siblings:value.siblings.map((row,i)=>i===index?{...row,name:e.target.value}:row)})}/><input className={styles.input} aria-label={`Sibling ${index+1} class and division`} placeholder="Class & division" required maxLength={100} value={s.class_division} onChange={e=>onChange({...value,siblings:value.siblings.map((row,i)=>i===index?{...row,class_division:e.target.value}:row)})}/><button className={styles.cancelBtn} type="button" onClick={()=>onChange({...value,siblings:value.siblings.filter((_,i)=>i!==index)})}>Remove</button></div>)}<button className={styles.changeBtn} type="button" disabled={value.siblings.length>=10} onClick={()=>onChange({...value,siblings:[...value.siblings,{name:'',class_division:''}]})}>+ Add sibling</button></section>
 <section><h2 className={styles.cardTitle}>Parent declaration</h2><p className={styles.hint}>Institution parent declaration. Record receipt of the parent’s signed form; staff are not accepting these terms for the parent.</p><ol className={local.declaration}>{declaration.map((line,i)=><li key={i}>{line}</li>)}</ol><div className={local.grid}>{field('declaration_parent','Signing parent’s name',200)}{field('declaration_date','Date',10,'date')}{field('declaration_place','Place',200)}</div><label className={local.checkbox}><input type="checkbox" checked={value.signed_declaration_received} onChange={e=>onChange({...value,signed_declaration_received:e.target.checked})}/>Signed declaration received</label><p className={styles.hint}>Upload the signed declaration and child’s photo in Documents after submission. A signed-declaration attachment is required before verification when receipt is marked above.</p></section>
 </div>
}
