"use client"
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { organisationApi, OrganisationSettings, bankingApi, MoneyAccount, BankTransfer, BankStatement } from '@/lib/api'
import PermissionGate from '@/components/access/PermissionGate'
import styles from '../invoices/create/create.module.css'
import table from '../statements/page.module.css'
import bankingStyles from './page.module.css'
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}` }
const money = (v: number | string | undefined) => `₹${Number(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

export default function BankingPage() {
    const { id } = useParams(); const institution = Number(id)
    const [organisation, setOrganisation] = useState<OrganisationSettings | null>(null)
    useEffect(() => { organisationApi.get().then(value => { setOrganisation(value); if (value.banking_mode === 'shared') setAccount(previous => ({ ...previous, kind: 'cash' })) }).catch(e => setError(e.message)) }, [])
    const [accounts, setAccounts] = useState<MoneyAccount[]>([])
    const [transfers, setTransfers] = useState<BankTransfer[]>([])
    const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
    const [version, setVersion] = useState(0)
    const [account, setAccount] = useState({ name: '', kind: 'bank', bank_name: '', account_last_four: '', opening_date: today(), opening_balance: '0' })
    const [transfer, setTransfer] = useState({ source_id: '', destination_id: '', transfer_date: today(), amount: '', reference: '', notes: '' })
    const [selected, setSelected] = useState(''); const [start, setStart] = useState(today()); const [end, setEnd] = useState(today())
    const [statement, setStatement] = useState<BankStatement | null>(null)
    const [statementError, setStatementError] = useState(''); const [loading, setLoading] = useState(false)
    useEffect(() => { let active = true; setAccounts([]); setTransfers([]); setError(''); Promise.all([bankingApi.accounts(institution), bankingApi.transfers(institution)]).then(([a, t]) => { if (active) { setAccounts(a); setTransfers(t) } }).catch(e => { if (active) setError(e.message) }); return () => { active = false } }, [institution, version])
    useEffect(() => { let active = true; setStatement(null); setStatementError(''); setLoading(Boolean(selected && start && end)); if (selected && start && end) bankingApi.statement(institution, Number(selected), start, end).then(s => { if (active) setStatement(s) }).catch(e => { if (active) setStatementError(e.message) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [institution, selected, start, end, version])
    const mutate = async (action: () => Promise<unknown>) => { setBusy(true); setError(''); try { await action(); setVersion(v => v + 1) } catch (e) { setError(e instanceof Error ? e.message : 'Request failed') } finally { setBusy(false) } }
    const accountName = (id: number) => accounts.find(a => a.id === id)?.name || `Account #${id}`
    return <div className={table.page}>
        <div className={styles.header}><h1 className={styles.title}>Bank & Cash</h1><p className={styles.sub}>Track account balances, deposits, withdrawals and bank transfers.</p></div>
        <p className={table.note}>Balances include opening amounts and assigned active transactions only. Unassigned historical receipts and expenses are excluded. Transfers move money between accounts without increasing income. Enter opening balances as of the start of the opening date; do not include transactions that you will record separately. This ledger tracks recorded payments, not bank clearance.</p>
        {error && <p className={styles.error} role="alert">{error}</p>}
        <div className={styles.form}>
            <section className={styles.card}><h2 className={styles.cardTitle}>Accounts</h2><div className={table.tableWrap}><table className={table.table}><thead><tr><th>Name</th><th>Type / Bank</th><th>Opening date</th><th>Opening balance</th><th>Statement</th></tr></thead><tbody>{accounts.map(a => <tr key={a.id}><td>{a.name}</td><td>{a.kind} {a.bank_name} {a.account_last_four ? `•••• ${a.account_last_four}` : ''}</td><td>{a.opening_date}</td><td>{money(a.opening_balance)}</td><td><button className={styles.changeBtn} onClick={() => { setSelected(String(a.id)); setStart(a.opening_date); setEnd(today() < a.opening_date ? a.opening_date : today()) }}>View</button></td></tr>)}</tbody></table></div>{!accounts.length && <p>No accounts yet.</p>}</section>
            {organisation?.banking_mode === "shared" && <p className={table.note}>Bank accounts are managed centrally in Organisation Setup. Shared account balances here include only this institution’s allocation and transactions. Cash accounts can be created below.</p>}
            <PermissionGate action="banking.create"><div className={bankingStyles.actionCards}>
            <section className={styles.card}><h2 className={styles.cardTitle}>Add Account</h2><form onSubmit={e => { e.preventDefault(); void mutate(async () => { await bankingApi.create(institution, { ...account, bank_name: account.kind === 'bank' ? account.bank_name : null, account_last_four: account.kind === 'bank' && account.account_last_four ? account.account_last_four : null }); setAccount({ ...account, name: '', account_last_four: '', opening_balance: '0' }) }) }}><fieldset disabled={busy} style={{ border: 0, padding: 0 }}><div className={bankingStyles.fields}>
                <label className={styles.field}>Account name<input className={styles.input} required maxLength={100} value={account.name} onChange={e => setAccount({ ...account, name: e.target.value })} /></label>
                <label className={styles.field}>Type<select className={styles.input} value={account.kind} onChange={e => setAccount({ ...account, kind: e.target.value })}><option value="bank" disabled={organisation?.banking_mode === "shared"}>Bank (central setup in shared mode)</option><option value="cash">Cash</option></select></label>
                {account.kind === 'bank' && <><label className={styles.field}>Bank name<input className={styles.input} maxLength={100} value={account.bank_name} onChange={e => setAccount({ ...account, bank_name: e.target.value })} /></label><label className={styles.field}>Account number (last four digits only)<input className={styles.input} pattern="[0-9]{4}" maxLength={4} value={account.account_last_four} onChange={e => setAccount({ ...account, account_last_four: e.target.value })} /></label></>}
                <label className={styles.field}>Opening date<input className={styles.input} required type="date" value={account.opening_date} onChange={e => setAccount({ ...account, opening_date: e.target.value })} /></label><label className={styles.field}>Opening balance<input className={styles.input} required type="number" step=".01" value={account.opening_balance} onChange={e => setAccount({ ...account, opening_balance: e.target.value })} /></label>
            </div><div className={`${styles.actions} ${bankingStyles.formActions}`}><button className={styles.submitBtn} disabled={busy}>Add Account</button></div></fieldset></form></section>
            <section className={styles.card}><h2 className={styles.cardTitle}>Transfer Money</h2><form onSubmit={e => { e.preventDefault(); void mutate(async () => { await bankingApi.transfer(institution, { ...transfer, source_id: Number(transfer.source_id), destination_id: Number(transfer.destination_id) }); setTransfer({ ...transfer, amount: '', reference: '', notes: '' }) }) }}><fieldset disabled={busy} style={{ border: 0, padding: 0 }}><div className={bankingStyles.fields}>
                {(['source_id', 'destination_id'] as const).map(key => <label key={key} className={styles.field}>{key === 'source_id' ? 'From account' : 'To account'}<select className={styles.input} required value={transfer[key]} onChange={e => setTransfer({ ...transfer, [key]: e.target.value })}><option value="">Select account</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label>)}
                <label className={styles.field}>Date<input className={styles.input} required type="date" value={transfer.transfer_date} onChange={e => setTransfer({ ...transfer, transfer_date: e.target.value })} /></label><label className={styles.field}>Amount<input className={styles.input} required type="number" min=".01" step=".01" value={transfer.amount} onChange={e => setTransfer({ ...transfer, amount: e.target.value })} /></label><label className={styles.field}>Reference<input className={styles.input} maxLength={100} value={transfer.reference} onChange={e => setTransfer({ ...transfer, reference: e.target.value })} /></label><label className={styles.field}>Notes<input className={styles.input} maxLength={500} value={transfer.notes} onChange={e => setTransfer({ ...transfer, notes: e.target.value })} /></label>
            </div><div className={`${styles.actions} ${bankingStyles.formActions}`}><button className={styles.submitBtn} disabled={busy}>Record Transfer</button></div></fieldset></form></section>
            </div></PermissionGate>
            <section className={styles.card}><h2 className={styles.cardTitle}>Account Statement</h2><div className={`${table.filters} ${bankingStyles.statementFilters}`}><label>Account<select value={selected} onChange={e => { setSelected(e.target.value); setStart(accounts.find(a => String(a.id) === e.target.value)?.opening_date || today()) }}><option value="">Select account</option>{accounts.map(a => <option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>From<input type="date" value={start} onChange={e => setStart(e.target.value)} /></label><label>To<input type="date" value={end} onChange={e => setEnd(e.target.value)} /></label></div>
                {loading ? <p>Loading…</p> : statementError ? <p role="alert">{statementError}</p> : statement && statement.account_id === Number(selected) && statement.start_date === start && statement.end_date === end && <><div className={table.summary}><div><span>Opening</span><strong>{money(statement.opening_balance)}</strong></div><div><span>Money in</span><strong>{money(statement.money_in)}</strong></div><div><span>Money out</span><strong>{money(statement.money_out)}</strong></div><div><span>Closing</span><strong>{money(statement.closing_balance)}</strong></div></div><div className={table.tableWrap}><table className={table.table}><thead><tr><th>Date</th><th>Type</th><th>Reference</th><th>In</th><th>Out</th><th>Balance</th></tr></thead><tbody>{statement.entries.map(r => <tr key={`${r.kind}-${r.id}`}><td>{r.date}</td><td>{r.kind}</td><td>{r.reference}</td><td>{money(r.money_in)}</td><td>{money(r.money_out)}</td><td>{money(r.balance)}</td></tr>)}</tbody></table></div>{!statement.entries.length && <p>No transactions in this period.</p>}</>}
            </section>
            <section className={styles.card}><h2 className={styles.cardTitle}>Transfers</h2><div className={table.tableWrap}><table className={table.table}><thead><tr><th>Date</th><th>From</th><th>To</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{transfers.map(t => <tr key={t.id}><td>{t.transfer_date}</td><td>{accountName(t.source_id)}</td><td>{accountName(t.destination_id)}</td><td>{money(t.amount)}</td><td>{t.status}{t.cancellation_reason && `: ${t.cancellation_reason}`}</td><td>{t.status === 'active' && <PermissionGate action="banking.delete"><button className={styles.cancelBtn} disabled={busy} onClick={() => { const reason = window.prompt('Reason for cancelling this transfer (both account entries will be reversed):'); if (reason?.trim()) void mutate(() => bankingApi.cancel(institution, t.id, reason.trim())) }}>Cancel transfer</button></PermissionGate>}</td></tr>)}</tbody></table></div></section>
        </div>
    </div>
}
