"use client"
import AdmissionFormView from '@/components/admission/AdmissionFormView'
import AdmissionProfile from '@/components/admission/AdmissionProfile'
import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import Link from 'next/link'
import { admissionApi, AdmissionApplication, AdmissionFormConfig } from '@/lib/api'
import { useUiAccess } from '@/components/access/PermissionGate'
import table from '../../accounts/statements/page.module.css'
import form from '../../accounts/invoices/create/create.module.css'
import styles from '../page.module.css'
export default function AdmissionDetailPage(){
 const {id,applicationId}=useParams();const institution=Number(id);const {can}=useUiAccess()
 const selected=Number(applicationId)
 const [version,setVersion]=useState(0)
 const [detail,setDetail]=useState<AdmissionApplication|null>(null)
 const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [busy,setBusy]=useState(false)
 const [formView,setFormView]=useState(false)
 const [documentType,setDocumentType]=useState('supporting')
 const [action,setAction]=useState('verify');const [notes,setNotes]=useState('');const [password,setPassword]=useState('');const [existing,setExisting]=useState(false);const [studentId,setStudentId]=useState('');const [query,setQuery]=useState('');const [students,setStudents]=useState<{id:number;name:string;email:string}[]>([])
 useEffect(()=>{
  let live=true;setLoading(true);setError('');setDetail(null);setNotes('');setPassword('');setStudentId('');setExisting(false);setQuery('')
  if(!Number.isSafeInteger(selected)||selected<=0){setError('Invalid application number');setLoading(false);return}
  admissionApi.detail(institution,selected).then(r=>{if(live)setDetail(r)}).catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)})
  return()=>{live=false}
 },[institution,selected,version])
 useEffect(()=>{let live=true;setStudents([]);setStudentId('');if(!existing||query.trim().length<2)return;const timer=setTimeout(()=>{admissionApi.students(institution,query).then(r=>{if(live)setStudents(r)}).catch(e=>{if(live)setError(e.message)})},250);return()=>{live=false;clearTimeout(timer)}},[institution,query,existing])
 const run=async(fn:()=>Promise<unknown>)=>{if(busy)return;setBusy(true);setError('');try{await fn();setVersion(v=>v+1)}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 const choices=detail?[...(detail.status==='verified'&&can('admission.verify')?['return_to_submitted']:[]),...(detail.status==='submitted'&&can('admission.verify')?['verify']:[]),...(detail.status==='verified'&&can('admission.admit')?['admit']:[]),...(['submitted','verified'].includes(detail.status)&&can('admission.verify')?['reject']:[]),...(['submitted','verified'].includes(detail.status)&&can('admission.update')?['withdraw']:[])]:[]
 const currentAction=choices.includes(action)?action:choices[0]||''
 const download=async(doc:{id:number;filename:string})=>{if(!detail)return;try{const blob=await admissionApi.document(institution,detail.id,doc.id);const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=doc.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setError(e instanceof Error?e.message:'Download failed')}}
 return <div className={table.page}>
 <div className={table.header}><div><Link className={form.backBtn} href={`/dashboard/institution/${id}/admission`}>← Back to applications</Link><h1 className={table.title}>Application Details</h1><p className={table.sub}>{detail?.reference || 'Admission application'}</p></div>{detail?.status==='submitted'&&can('admission.update')&&<Link className={form.submitBtn} href={`/dashboard/institution/${id}/admission/${detail.id}/edit`}>Edit Application</Link>}</div>
 {error&&<p className={form.error} role="alert">{error}</p>}
 {loading&&<p role="status">Loading application…</p>}
 {detail&&<div style={{display:'flex',gap:'.75rem',marginBottom:'1rem'}}><button type="button" className={form.changeBtn} aria-pressed={!formView} onClick={()=>setFormView(false)}>Details</button><button type="button" className={form.changeBtn} aria-pressed={formView} onClick={()=>setFormView(true)}>Form View</button></div>}
 {detail&&<div className={form.form}>
 {formView?<AdmissionFormView application={detail}/>:<>
 <section className={form.card}><h2 className={`${form.cardTitle} ${styles.sectionTitle}`}>{detail.reference} <span className={`${styles.badge} ${styles[detail.status]}`}>{detail.status}</span></h2><table className={styles.details} aria-label="Applicant details"><tbody>{(['applicant_name','email','phone','date_of_birth','gender','address','guardian_name','guardian_phone','academic_year','grade','notes'] as const).filter(key=>detail.template_version!=='common_v1'||!['email','phone','notes'].includes(key)).map(key=><tr key={key}><th scope="row">{key.replaceAll('_',' ')}</th><td>{detail[key]||'—'}</td></tr>)}</tbody></table>{detail.admission_number&&<p><strong>Admission number: {detail.admission_number}</strong></p>}{detail.student_id&&can('students.read')&&<Link href={`/dashboard/institution/${id}/users/${detail.student_id}/view`}>View student →</Link>}</section>
 {detail.extra_data&&<section className={form.card}><h2 className={`${form.cardTitle} ${styles.sectionTitle}`}>Additional application details</h2><AdmissionProfile data={detail.extra_data}/>{detail.admitted_on&&<p>Admission date: {detail.admitted_on}</p>}</section>}
 </>}
 <section className={form.card}><h2 className={`${form.cardTitle} ${styles.sectionTitle}`}>Documents</h2>{(detail.extra_data?._form as AdmissionFormConfig|undefined)?.required_documents.length? <p className={form.hint}>Required before verification: {(detail.extra_data?._form as AdmissionFormConfig).required_documents.map(d=>d.replaceAll('_',' ')).join(', ')}</p>:null}<p className={form.hint}>Private PDF, PNG or JPEG files, up to 8 MB. Documents are locked after verification.</p>{detail.status==='submitted'&&can('admission.upload')&&<div className={styles.uploadRow}><label className={form.field}>Supporting document<select className={form.input} value={documentType} onChange={e=>setDocumentType(e.target.value)}><option value="supporting">Document</option><option value="birth_certificate">Birth Certificate</option><option value="tc">TC</option><option value="recommendation_letter">Recommendation Letter</option><option value="photo">Child photo</option><option value="signed_declaration">Signed declaration</option></select></label><label className={form.field}>Choose file<input className={styles.fileInput} type="file" disabled={busy} accept="application/pdf,image/png,image/jpeg" onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file){if(file.size>8*1024*1024){setError('Maximum file size is 8 MB');return}void run(()=>admissionApi.upload(institution,detail.id,file,documentType))}}}/></label></div>}<ul>{detail.documents?.map(d=><li key={d.id}><button className={form.changeBtn} onClick={()=>void download(d)}>{d.document_type?.replaceAll('_',' ')}: {d.filename}</button>{detail.status==='submitted'&&can('admission.upload')&&<button type="button" disabled={busy} className={form.cancelBtn} style={{marginLeft:'.75rem'}} onClick={()=>{if(window.confirm(`Remove ${d.filename}? You can upload a replacement afterwards.`))void run(()=>admissionApi.removeDocument(institution,detail.id,d.id))}}>Remove</button>}</li>)}</ul></section>
 {choices.length>0&&<section className={form.card}><h2 className={`${form.cardTitle} ${styles.sectionTitle}`}>Admission decision</h2><form onSubmit={e=>{e.preventDefault();if(!window.confirm(`Confirm ${currentAction.replaceAll('_',' ')} for ${detail.applicant_name}?`))return;void run(()=>admissionApi.action(institution,detail.id,{action:currentAction,notes,password:currentAction==='admit'&&!existing&&!['alfitrah_v1','common_v1'].includes(detail.template_version)?password:null,existing_user_id:currentAction==='admit'&&existing?Number(studentId):null}))}}><fieldset disabled={busy} style={{border:0,padding:0}}>
 <label className={form.field}>Action<select className={form.input} value={currentAction} onChange={e=>setAction(e.target.value)}>{choices.map(c=><option key={c} value={c}>{c==='return_to_submitted'?'Return to Submitted':c}</option>)}</select></label>
 {currentAction==='admit'&&<><label className={form.field}>Student record<select className={form.input} value={String(existing)} onChange={e=>setExisting(e.target.value==='true')}><option value="false">Create new student</option><option value="true">Link existing student</option></select></label>{existing?<><label className={form.field}>Search student by name or email<input className={form.input} value={query} onChange={e=>setQuery(e.target.value)}/></label><label className={form.field}>Matching student<select className={form.input} required value={studentId} onChange={e=>setStudentId(e.target.value)}><option value="">Select student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name} — {s.email}</option>)}</select></label><p className={form.hint}>The student must belong to this institution and match the class and academic year. Without an applicant email, name, date of birth and guardian phone must match.</p></>:['alfitrah_v1','common_v1'].includes(detail.template_version)?<p className={form.hint}>Create a student record without issuing login credentials.</p>:<label className={form.field}>Initial student password<input className={form.input} type="password" autoComplete="new-password" required minLength={8} maxLength={72} value={password} onChange={e=>setPassword(e.target.value)}/></label>}</>}
 <label className={form.field}>Notes / reason<textarea className={form.input} required maxLength={5000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><button className={form.submitBtn} style={{marginTop:'1rem'}}>{busy?'Saving…':'Confirm Action'}</button></fieldset></form></section>}
 <section className={form.card}><h2 className={`${form.cardTitle} ${styles.sectionTitle}`}>Activity history</h2>{detail.events?.map(event=><article className={styles.event} key={event.id}><strong>{event.action} — {event.actor_name}</strong><p>{new Date(event.created_at.endsWith('Z')?event.created_at:event.created_at+'Z').toLocaleString()}</p><p>{event.notes}</p></article>)}</section>
 </div>}</div>
}
