"use client"
import LoginBrandingPanel from "@/components/organisation/LoginBrandingPanel"
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { organisationApi, institutionsApi, OrganisationSettings, MoneyAccount, BankStatement } from '@/lib/api'
import { Institution } from '@/types/institution'
import styles from '../institution/[id]/accounts/invoices/create/create.module.css'
import table from '../institution/[id]/accounts/statements/page.module.css'
const today = () => { const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}` }
const money=(v:string|number)=>Number(v).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2})
export default function OrganisationPage(){
 const [settings,setSettings]=useState<OrganisationSettings|null>(null)
 const [name,setName]=useState(''); const [mode,setMode]=useState('independent'); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
 const [institutions,setInstitutions]=useState<Institution[]>([]);const [banks,setBanks]=useState<MoneyAccount[]>([])
 const [allocation,setAllocation]=useState<Record<number,string>>({})
 const [bank,setBank]=useState({name:'',bank_name:'',account_last_four:'',opening_date:today()})
 const [selected,setSelected]=useState('');const [start,setStart]=useState(today());const [end,setEnd]=useState(today());const [report,setReport]=useState<BankStatement|null>(null)
 const [linkInstitution,setLinkInstitution]=useState('')
 const [success,setSuccess]=useState('')
 useEffect(()=>{organisationApi.get().then(s=>{setSettings(s);setName(s.name);setMode(s.banking_mode || 'independent');if(s.can_manage)Promise.all([institutionsApi.getAll(),organisationApi.banks()]).then(([i,b])=>{setInstitutions(i);setBanks(b)}).catch(e=>setError(e.message))}).catch(e=>setError(e.message))},[])
 useEffect(()=>{let active=true;setReport(null);if(selected && start && end)organisationApi.statement(Number(selected),start,end).then(r=>{if(active)setReport(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[selected,start,end])
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setSuccess('');try{await fn()}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
 if(!settings)return <p role="status">{error || 'Loading organisation setup…'}</p>
 if(!settings.can_manage)return <p>Organisation setup requires superadmin access.</p>
 return <div className={table.page}><Link href="/dashboard">← Institutions</Link><h1 className={styles.title}>Organisation Setup</h1>
 {error && <p className={styles.error} role="alert">{error}</p>}{success && <p role="status">{success}</p>}
 <div className={styles.form}><section className={styles.card}><h2 className={styles.cardTitle}>Deployment Settings</h2><form onSubmit={e=>{e.preventDefault();void run(async()=>{setSettings(await organisationApi.save({name,banking_mode:mode}));setSuccess('Organisation settings saved.')})}}><fieldset disabled={busy} style={{border:0,padding:0}}><div className={styles.grid2}>
 <label className={styles.field}>Organisation name<input className={styles.input} required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/></label>
 <label className={styles.field}>Banking mode<select className={styles.input} value={mode} disabled={settings.banking_locked} onChange={e=>setMode(e.target.value)}><option value="independent">Independent — each institution manages its bank accounts</option><option value="shared">Shared — bank accounts are managed centrally</option></select></label></div>
 <p className={styles.hint}>{settings.banking_locked?'Shared banking is required while central accounts exist.':'You can enable shared banking with existing accounts. Existing accounts and balances stay with their institutions; create central accounts for sharing. Cash accounts always belong to individual institutions.'}</p><button className={styles.submitBtn}>Save Settings</button></fieldset></form></section>
 {settings.configured && <LoginBrandingPanel />}
 {settings.configured && settings.banking_mode==='shared' && <section className={styles.card}><h2 className={styles.cardTitle}>Create Central Bank Account</h2><p className={styles.sub}>Link one or more institutions. Allocate the opening balance once across these institutions; their amounts must add up to the real bank opening balance.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await organisationApi.createBank({...bank,account_last_four:bank.account_last_four || null,institutions:Object.entries(allocation).map(([institution_id,opening_balance])=>({institution_id:Number(institution_id),opening_balance:opening_balance || '0'}))});setBanks(await organisationApi.banks());setSettings(await organisationApi.get());setBank({...bank,name:'',account_last_four:''});setAllocation({});setSuccess('Bank account created and linked.')})}}><fieldset disabled={busy} style={{border:0,padding:0}}><div className={styles.grid2}>
 {(['name','bank_name','account_last_four','opening_date'] as const).map(key=><label className={styles.field} key={key}>{{name:'Account name',bank_name:'Bank name',account_last_four:'Last four digits (optional)',opening_date:'Opening date'}[key]}<input className={styles.input} required={key!=='account_last_four'} type={key==='opening_date'?'date':'text'} pattern={key==='account_last_four'?'[0-9]{4}':undefined} maxLength={key==='account_last_four'?4:100} value={bank[key]} onChange={e=>setBank({...bank,[key]:e.target.value})}/></label>)}</div>
 {institutions.filter(i=>i.is_active).map(i=><div key={i.id} className={styles.grid2}><label><input type="checkbox" checked={i.id in allocation} onChange={e=>setAllocation(previous=>{const next={...previous};if(e.target.checked)next[i.id]='0';else delete next[i.id];return next})}/> {i.name}</label>{i.id in allocation && <label className={styles.field}>Allocated opening balance<input className={styles.input} type="number" step=".01" required value={allocation[i.id]} onChange={e=>setAllocation({...allocation,[i.id]:e.target.value})}/></label>}</div>)}
 <p className={styles.hint}>Total bank opening balance: ₹{money(Object.values(allocation).reduce((sum,v)=>sum+Number(v||0),0))}</p><button className={styles.submitBtn} disabled={!Object.keys(allocation).length}>Create Bank Account</button></fieldset></form></section>}
 <section className={styles.card}><h2 className={styles.cardTitle}>Central Bank Statement</h2><p className={styles.sub}>Combined account balance and transactions across linked institutions. Only the superadmin can view this report.</p><div className={table.filters}><label>Account<select value={selected} onChange={e=>{setSelected(e.target.value);setStart(banks.find(b=>String(b.id)===e.target.value)?.opening_date || today())}}><option value="">Select bank</option>{banks.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
 {settings.banking_mode==='shared' && selected && banks.find(b=>String(b.id)===selected)?.institution_id === null && <div className={table.filters}><label>Link another institution (zero opening allocation)<select value={linkInstitution} onChange={e=>setLinkInstitution(e.target.value)}><option value="">Select institution</option>{institutions.filter(i=>i.is_active).map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></label><button className={styles.changeBtn} disabled={busy || !linkInstitution} onClick={()=>void run(async()=>{await organisationApi.linkBank(Number(selected),Number(linkInstitution));setSuccess('Institution linked. Existing opening allocations are unchanged.');setLinkInstitution('')})}>Link Institution</button></div>}
 {report && report.account_id===Number(selected) && report.start_date===start && report.end_date===end && <><p className={styles.hint}>Opening ₹{money(report.opening_balance)} · Closing ₹{money(report.closing_balance)}</p><div className={table.tableWrap}><table className={table.table}><thead><tr><th>Date</th><th>Institution</th><th>Reference</th><th>In</th><th>Out</th><th>Balance</th></tr></thead><tbody>{report.entries.map(r=><tr key={`${r.kind}-${r.id}`}><td>{r.date}</td><td>{institutions.find(i=>i.id===r.institution_id)?.name || r.institution_id}</td><td>{r.reference}</td><td>{money(r.money_in)}</td><td>{money(r.money_out)}</td><td>{money(r.balance)}</td></tr>)}</tbody></table></div></>}
 </section></div></div>
}
